apiVersion: v1
kind: Service
metadata:
  name: jw-news-reader-api
  labels:
    app: jw-news-reader-api
spec:
  type: ClusterIP
  selector:
    app: jw-news-reader-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
